configuration:  
  projectName: passport-office

spring:
    profiles: en
        server:
            port: 4200
        message:
            greeting: Hello from the configuration!
  

    profiles: ru
        server:
            port: 4200
        message:
            greeting: Привет от сервера конфигурации!